//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace avanak
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="avanak.WebService3Soap")]
    public interface WebService3Soap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> RegisterAsync(string userName, string password, string fullname, string mobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecoverPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<avanak.Result> RecoverPasswordAsync(string userName, string mobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<avanak.Result> ChangePasswordAsync(string userName, string password, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProfile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<avanak.Profile> GetProfileAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadMessageBase64", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> UploadMessageBase64Async(string userName, string password, string title, string base64, bool Persist, string CallFromMobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<avanak.UploadMessageResponse> UploadMessageAsync(avanak.UploadMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateTTS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> GenerateTTSAsync(string userName, string password, string speaker, string text, string title, string CallFromMobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateTTS2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<avanak.TTSResult> GenerateTTS2Async(string userName, string password, string speaker, string text, string title, string CallFromMobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> DeleteMessageAsync(string userName, string password, int messageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateCampaign", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<long> CreateCampaignAsync(string userName, string password, string title, string numbers, int maxTryCount, int minuteBetweenTries, string startDate, string startTime, string endDate, string endTime, int messageId, bool removeInvalids, int serverId, bool autoStart, bool vote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateCampaignGIS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<long> CreateCampaignGISAsync(
                    string userName, 
                    string password, 
                    string title, 
                    string numbers, 
                    string GISCroods, 
                    int maxTryCount, 
                    int minuteBetweenTries, 
                    string startDate, 
                    string startTime, 
                    string endDate, 
                    string endTime, 
                    int messageId, 
                    bool removeInvalids, 
                    int serverId, 
                    bool autoStart, 
                    bool vote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StartCampaign", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<long> StartCampaignAsync(string userName, string password, long campaignId, string title, int minuteBetweenTries, int maxTryCount, string startDate, string endDate, string startTime, string endTime, int serverid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StopCampaign", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> StopCampaignAsync(string userName, string password, long campaignId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCampaignsByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<avanak.Campaign[]> GetCampaignsByDateAsync(string userName, string password, string fromDate, string toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCampaignById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<avanak.Campaign> GetCampaignByIdAsync(string userName, string password, long campaignId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCampaignNumbersByCampaignId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<avanak.Numbers[]> GetCampaignNumbersByCampaignIdAsync(string userName, string password, long campaignId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCampaignNumbersBySubscribeId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<avanak.Numbers> GetCampaignNumbersBySubscribeIdAsync(string userName, string password, long subscribeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCampaignNumbersByMessageId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<avanak.Numbers[]> GetCampaignNumbersByMessageIdAsync(string userName, string password, long messageId, int lastid, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCampaignNumbersBySendDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<avanak.Numbers[]> GetCampaignNumbersBySendDateAsync(string userName, string password, string fromDate, string toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCampaignNumbersDataByIds", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<avanak.Numbers[]> GetCampaignNumbersDataByIdsAsync(string userName, string password, string campaignNumberIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCampaignNumberStatusById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<avanak.GetCampaignNumberStatusByIdResponse> GetCampaignNumberStatusByIdAsync(avanak.GetCampaignNumberStatusByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCampaignNumbersStatusByIds", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int[]> GetCampaignNumbersStatusByIdsAsync(string userName, string password, string campaignNumberIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QuickSend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> QuickSendAsync(string userName, string password, int messageId, string number, bool vote, int serverid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QuickSendWithTTS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> QuickSendWithTTSAsync(string userName, string password, string text, string number, bool vote, int serverid, string CallFromMobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendOTP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> SendOTPAsync(string userName, string password, int Length, string number, string text, int serverid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendOCV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<avanak.OCVSend> SendOCVAsync(string userName, string password, string number, string callbackUrl, int serverid);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQuickSend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<avanak.GetQuickSendResponse> GetQuickSendAsync(avanak.GetQuickSendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTotalCostByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<decimal> GetTotalCostByDateAsync(string userName, string password, string fromDate, string toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<avanak.Message> GetMessageAsync(string userName, string password, int messageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<avanak.Message[]> GetMessagesAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessagesByPage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<avanak.MessagesByPage> GetMessagesByPageAsync(string userName, string password, bool showPersist, int count, int currentpage, string order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownloadMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<avanak.DownloadMessageResponse> DownloadMessageAsync(avanak.DownloadMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCredit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<decimal> GetCreditAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetExpirationDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetExpirationDateAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPrices", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<avanak.PriceViewModel> GetPricesAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccountInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<avanak.UserInfo> GetAccountInfoAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTransactions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<avanak.Transactions[]> GetTransactionsAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> AddTicketAsync(string userName, string password, string title, string text, int priority);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTickets", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<avanak.Ticket[]> GetTicketsAsync(string userName, string password, int lastId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTicketStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> GetTicketStatusAsync(string userName, string password, int ticketId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MakeSecureCall", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> MakeSecureCallAsync(string userName, string password, string srcNumber, string dstNumber, int holdMessageId, int serverId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAreaByNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> GetAreaByNumberAsync(string userName, string password, string number);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Result
    {
        
        private bool resultField;
        
        private int codeField;
        
        private string[] messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public string[] message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Ticket
    {
        
        private string titleField;
        
        private string fullNameField;
        
        private string mobileField;
        
        private string textField;
        
        private System.DateTime createDateField;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Mobile
        {
            get
            {
                return this.mobileField;
            }
            set
            {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime CreateDate
        {
            get
            {
                return this.createDateField;
            }
            set
            {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Transactions
    {
        
        private decimal amountField;
        
        private System.DateTime createDateField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime CreateDate
        {
            get
            {
                return this.createDateField;
            }
            set
            {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserInfo
    {
        
        private string nameField;
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PriceViewModel
    {
        
        private decimal addClientPriceField;
        
        private decimal addClientRateField;
        
        private decimal addResellerPriceField;
        
        private decimal addResellerRateField;
        
        private decimal externalSecondPriceField;
        
        private decimal gPSSecondPriceField;
        
        private decimal gPSSecondRateField;
        
        private int idField;
        
        private decimal internalSecondPriceField;
        
        private decimal lBSSecondPriceField;
        
        private decimal lBSSecondRateField;
        
        private decimal maximumDebtField;
        
        private decimal poolSecondPriceField;
        
        private decimal poolSecondRateField;
        
        private int priceInSecondField;
        
        private int pulseDurationField;
        
        private decimal pulseOffRateField;
        
        private System.Nullable<int> resellerIdField;
        
        private string resultField;
        
        private string titleField;
        
        private decimal tTSSecondPriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal AddClientPrice
        {
            get
            {
                return this.addClientPriceField;
            }
            set
            {
                this.addClientPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal AddClientRate
        {
            get
            {
                return this.addClientRateField;
            }
            set
            {
                this.addClientRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal AddResellerPrice
        {
            get
            {
                return this.addResellerPriceField;
            }
            set
            {
                this.addResellerPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal AddResellerRate
        {
            get
            {
                return this.addResellerRateField;
            }
            set
            {
                this.addResellerRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal ExternalSecondPrice
        {
            get
            {
                return this.externalSecondPriceField;
            }
            set
            {
                this.externalSecondPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal GPSSecondPrice
        {
            get
            {
                return this.gPSSecondPriceField;
            }
            set
            {
                this.gPSSecondPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal GPSSecondRate
        {
            get
            {
                return this.gPSSecondRateField;
            }
            set
            {
                this.gPSSecondRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal InternalSecondPrice
        {
            get
            {
                return this.internalSecondPriceField;
            }
            set
            {
                this.internalSecondPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal LBSSecondPrice
        {
            get
            {
                return this.lBSSecondPriceField;
            }
            set
            {
                this.lBSSecondPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal LBSSecondRate
        {
            get
            {
                return this.lBSSecondRateField;
            }
            set
            {
                this.lBSSecondRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public decimal MaximumDebt
        {
            get
            {
                return this.maximumDebtField;
            }
            set
            {
                this.maximumDebtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal PoolSecondPrice
        {
            get
            {
                return this.poolSecondPriceField;
            }
            set
            {
                this.poolSecondPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public decimal PoolSecondRate
        {
            get
            {
                return this.poolSecondRateField;
            }
            set
            {
                this.poolSecondRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int PriceInSecond
        {
            get
            {
                return this.priceInSecondField;
            }
            set
            {
                this.priceInSecondField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int PulseDuration
        {
            get
            {
                return this.pulseDurationField;
            }
            set
            {
                this.pulseDurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public decimal PulseOffRate
        {
            get
            {
                return this.pulseOffRateField;
            }
            set
            {
                this.pulseOffRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<int> ResellerId
        {
            get
            {
                return this.resellerIdField;
            }
            set
            {
                this.resellerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public decimal TTSSecondPrice
        {
            get
            {
                return this.tTSSecondPriceField;
            }
            set
            {
                this.tTSSecondPriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MessagesByPage
    {
        
        private int countField;
        
        private Message[] messagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Message[] Messages
        {
            get
            {
                return this.messagesField;
            }
            set
            {
                this.messagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Message
    {
        
        private int idField;
        
        private string titleField;
        
        private int lenghtField;
        
        private bool isDefaultField;
        
        private bool showInGalleryField;
        
        private int confirmedField;
        
        private System.DateTime createDateField;
        
        private int internalPriceField;
        
        private int externalPriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Lenght
        {
            get
            {
                return this.lenghtField;
            }
            set
            {
                this.lenghtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool IsDefault
        {
            get
            {
                return this.isDefaultField;
            }
            set
            {
                this.isDefaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool ShowInGallery
        {
            get
            {
                return this.showInGalleryField;
            }
            set
            {
                this.showInGalleryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Confirmed
        {
            get
            {
                return this.confirmedField;
            }
            set
            {
                this.confirmedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime CreateDate
        {
            get
            {
                return this.createDateField;
            }
            set
            {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int InternalPrice
        {
            get
            {
                return this.internalPriceField;
            }
            set
            {
                this.internalPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int ExternalPrice
        {
            get
            {
                return this.externalPriceField;
            }
            set
            {
                this.externalPriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CDRDetails
    {
        
        private string dstField;
        
        private int durationField;
        
        private string idField;
        
        private int reasonField;
        
        private string starttimeField;
        
        private string statusField;
        
        private long subscribeidField;
        
        private int voteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dst
        {
            get
            {
                return this.dstField;
            }
            set
            {
                this.dstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int reason
        {
            get
            {
                return this.reasonField;
            }
            set
            {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string starttime
        {
            get
            {
                return this.starttimeField;
            }
            set
            {
                this.starttimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long subscribeid
        {
            get
            {
                return this.subscribeidField;
            }
            set
            {
                this.subscribeidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int vote
        {
            get
            {
                return this.voteField;
            }
            set
            {
                this.voteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OCVSend
    {
        
        private int resultField;
        
        private int codeField;
        
        private int sendIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int SendId
        {
            get
            {
                return this.sendIdField;
            }
            set
            {
                this.sendIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Numbers
    {
        
        private int idField;
        
        private long campaignIDField;
        
        private string numberField;
        
        private int durationField;
        
        private int tryCountField;
        
        private bool isMobileField;
        
        private long requestIdField;
        
        private decimal priceField;
        
        private long statusField;
        
        private string sendDateField;
        
        private string deliverDateField;
        
        private int voteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long CampaignID
        {
            get
            {
                return this.campaignIDField;
            }
            set
            {
                this.campaignIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int TryCount
        {
            get
            {
                return this.tryCountField;
            }
            set
            {
                this.tryCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool IsMobile
        {
            get
            {
                return this.isMobileField;
            }
            set
            {
                this.isMobileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long RequestId
        {
            get
            {
                return this.requestIdField;
            }
            set
            {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal Price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string SendDate
        {
            get
            {
                return this.sendDateField;
            }
            set
            {
                this.sendDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string DeliverDate
        {
            get
            {
                return this.deliverDateField;
            }
            set
            {
                this.deliverDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int Vote
        {
            get
            {
                return this.voteField;
            }
            set
            {
                this.voteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Campaign
    {
        
        private int idField;
        
        private string campaignTitleField;
        
        private int messageIdField;
        
        private string messageTitleField;
        
        private int maxTryCountField;
        
        private int minuteBetweenTriesField;
        
        private string startDateField;
        
        private string startTimeField;
        
        private string endDateField;
        
        private string endTimeField;
        
        private long internalCountField;
        
        private long externalCountField;
        
        private decimal totalPriceField;
        
        private bool voteField;
        
        private int statusIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CampaignTitle
        {
            get
            {
                return this.campaignTitleField;
            }
            set
            {
                this.campaignTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int MessageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MessageTitle
        {
            get
            {
                return this.messageTitleField;
            }
            set
            {
                this.messageTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int MaxTryCount
        {
            get
            {
                return this.maxTryCountField;
            }
            set
            {
                this.maxTryCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int MinuteBetweenTries
        {
            get
            {
                return this.minuteBetweenTriesField;
            }
            set
            {
                this.minuteBetweenTriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string StartTime
        {
            get
            {
                return this.startTimeField;
            }
            set
            {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string EndTime
        {
            get
            {
                return this.endTimeField;
            }
            set
            {
                this.endTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public long InternalCount
        {
            get
            {
                return this.internalCountField;
            }
            set
            {
                this.internalCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public long ExternalCount
        {
            get
            {
                return this.externalCountField;
            }
            set
            {
                this.externalCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal TotalPrice
        {
            get
            {
                return this.totalPriceField;
            }
            set
            {
                this.totalPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool Vote
        {
            get
            {
                return this.voteField;
            }
            set
            {
                this.voteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int StatusId
        {
            get
            {
                return this.statusIdField;
            }
            set
            {
                this.statusIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TTSResult
    {
        
        private int idField;
        
        private int lengthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Length
        {
            get
            {
                return this.lengthField;
            }
            set
            {
                this.lengthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Profile
    {
        
        private int resultField;
        
        private string userNameField;
        
        private string fullNameField;
        
        private string mobileField;
        
        private string expireDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Mobile
        {
            get
            {
                return this.mobileField;
            }
            set
            {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ExpireDate
        {
            get
            {
                return this.expireDateField;
            }
            set
            {
                this.expireDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string title;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public bool Persist;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string CallFromMobile;
        
        public UploadMessageRequest()
        {
        }
        
        public UploadMessageRequest(string userName, string password, string title, byte[] file, bool Persist, string CallFromMobile)
        {
            this.userName = userName;
            this.password = password;
            this.title = title;
            this.file = file;
            this.Persist = Persist;
            this.CallFromMobile = CallFromMobile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadMessageResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int UploadMessageResult;
        
        public UploadMessageResponse()
        {
        }
        
        public UploadMessageResponse(int UploadMessageResult)
        {
            this.UploadMessageResult = UploadMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCampaignNumberStatusById", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCampaignNumberStatusByIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public long campaignNumberId;
        
        public GetCampaignNumberStatusByIdRequest()
        {
        }
        
        public GetCampaignNumberStatusByIdRequest(string userName, string password, long campaignNumberId)
        {
            this.userName = userName;
            this.password = password;
            this.campaignNumberId = campaignNumberId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCampaignNumberStatusByIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCampaignNumberStatusByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> GetCampaignNumberStatusByIdResult;
        
        public GetCampaignNumberStatusByIdResponse()
        {
        }
        
        public GetCampaignNumberStatusByIdResponse(System.Nullable<int> GetCampaignNumberStatusByIdResult)
        {
            this.GetCampaignNumberStatusByIdResult = GetCampaignNumberStatusByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetQuickSend", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetQuickSendRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int quickSendId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public decimal price;
        
        public GetQuickSendRequest()
        {
        }
        
        public GetQuickSendRequest(string userName, string password, int quickSendId, decimal price)
        {
            this.userName = userName;
            this.password = password;
            this.quickSendId = quickSendId;
            this.price = price;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetQuickSendResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetQuickSendResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public avanak.CDRDetails GetQuickSendResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public decimal price;
        
        public GetQuickSendResponse()
        {
        }
        
        public GetQuickSendResponse(avanak.CDRDetails GetQuickSendResult, decimal price)
        {
            this.GetQuickSendResult = GetQuickSendResult;
            this.price = price;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int messageId;
        
        public DownloadMessageRequest()
        {
        }
        
        public DownloadMessageRequest(string userName, string password, int messageId)
        {
            this.userName = userName;
            this.password = password;
            this.messageId = messageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadMessageResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DownloadMessageResult;
        
        public DownloadMessageResponse()
        {
        }
        
        public DownloadMessageResponse(byte[] DownloadMessageResult)
        {
            this.DownloadMessageResult = DownloadMessageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface WebService3SoapChannel : avanak.WebService3Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WebService3SoapClient : System.ServiceModel.ClientBase<avanak.WebService3Soap>, avanak.WebService3Soap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebService3SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebService3SoapClient.GetBindingForEndpoint(endpointConfiguration), WebService3SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService3SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebService3SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService3SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebService3SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService3SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<int> RegisterAsync(string userName, string password, string fullname, string mobile)
        {
            return base.Channel.RegisterAsync(userName, password, fullname, mobile);
        }
        
        public System.Threading.Tasks.Task<avanak.Result> RecoverPasswordAsync(string userName, string mobile)
        {
            return base.Channel.RecoverPasswordAsync(userName, mobile);
        }
        
        public System.Threading.Tasks.Task<avanak.Result> ChangePasswordAsync(string userName, string password, string newPassword)
        {
            return base.Channel.ChangePasswordAsync(userName, password, newPassword);
        }
        
        public System.Threading.Tasks.Task<avanak.Profile> GetProfileAsync(string userName, string password)
        {
            return base.Channel.GetProfileAsync(userName, password);
        }
        
        public System.Threading.Tasks.Task<int> UploadMessageBase64Async(string userName, string password, string title, string base64, bool Persist, string CallFromMobile)
        {
            return base.Channel.UploadMessageBase64Async(userName, password, title, base64, Persist, CallFromMobile);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<avanak.UploadMessageResponse> avanak.WebService3Soap.UploadMessageAsync(avanak.UploadMessageRequest request)
        {
            return base.Channel.UploadMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<avanak.UploadMessageResponse> UploadMessageAsync(string userName, string password, string title, byte[] file, bool Persist, string CallFromMobile)
        {
            avanak.UploadMessageRequest inValue = new avanak.UploadMessageRequest();
            inValue.userName = userName;
            inValue.password = password;
            inValue.title = title;
            inValue.file = file;
            inValue.Persist = Persist;
            inValue.CallFromMobile = CallFromMobile;
            return ((avanak.WebService3Soap)(this)).UploadMessageAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<int> GenerateTTSAsync(string userName, string password, string speaker, string text, string title, string CallFromMobile)
        {
            return base.Channel.GenerateTTSAsync(userName, password, speaker, text, title, CallFromMobile);
        }
        
        public System.Threading.Tasks.Task<avanak.TTSResult> GenerateTTS2Async(string userName, string password, string speaker, string text, string title, string CallFromMobile)
        {
            return base.Channel.GenerateTTS2Async(userName, password, speaker, text, title, CallFromMobile);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteMessageAsync(string userName, string password, int messageId)
        {
            return base.Channel.DeleteMessageAsync(userName, password, messageId);
        }
        
        public System.Threading.Tasks.Task<long> CreateCampaignAsync(string userName, string password, string title, string numbers, int maxTryCount, int minuteBetweenTries, string startDate, string startTime, string endDate, string endTime, int messageId, bool removeInvalids, int serverId, bool autoStart, bool vote)
        {
            return base.Channel.CreateCampaignAsync(userName, password, title, numbers, maxTryCount, minuteBetweenTries, startDate, startTime, endDate, endTime, messageId, removeInvalids, serverId, autoStart, vote);
        }
        
        public System.Threading.Tasks.Task<long> CreateCampaignGISAsync(
                    string userName, 
                    string password, 
                    string title, 
                    string numbers, 
                    string GISCroods, 
                    int maxTryCount, 
                    int minuteBetweenTries, 
                    string startDate, 
                    string startTime, 
                    string endDate, 
                    string endTime, 
                    int messageId, 
                    bool removeInvalids, 
                    int serverId, 
                    bool autoStart, 
                    bool vote)
        {
            return base.Channel.CreateCampaignGISAsync(userName, password, title, numbers, GISCroods, maxTryCount, minuteBetweenTries, startDate, startTime, endDate, endTime, messageId, removeInvalids, serverId, autoStart, vote);
        }
        
        public System.Threading.Tasks.Task<long> StartCampaignAsync(string userName, string password, long campaignId, string title, int minuteBetweenTries, int maxTryCount, string startDate, string endDate, string startTime, string endTime, int serverid)
        {
            return base.Channel.StartCampaignAsync(userName, password, campaignId, title, minuteBetweenTries, maxTryCount, startDate, endDate, startTime, endTime, serverid);
        }
        
        public System.Threading.Tasks.Task<bool> StopCampaignAsync(string userName, string password, long campaignId)
        {
            return base.Channel.StopCampaignAsync(userName, password, campaignId);
        }
        
        public System.Threading.Tasks.Task<avanak.Campaign[]> GetCampaignsByDateAsync(string userName, string password, string fromDate, string toDate)
        {
            return base.Channel.GetCampaignsByDateAsync(userName, password, fromDate, toDate);
        }
        
        public System.Threading.Tasks.Task<avanak.Campaign> GetCampaignByIdAsync(string userName, string password, long campaignId)
        {
            return base.Channel.GetCampaignByIdAsync(userName, password, campaignId);
        }
        
        public System.Threading.Tasks.Task<avanak.Numbers[]> GetCampaignNumbersByCampaignIdAsync(string userName, string password, long campaignId)
        {
            return base.Channel.GetCampaignNumbersByCampaignIdAsync(userName, password, campaignId);
        }
        
        public System.Threading.Tasks.Task<avanak.Numbers> GetCampaignNumbersBySubscribeIdAsync(string userName, string password, long subscribeId)
        {
            return base.Channel.GetCampaignNumbersBySubscribeIdAsync(userName, password, subscribeId);
        }
        
        public System.Threading.Tasks.Task<avanak.Numbers[]> GetCampaignNumbersByMessageIdAsync(string userName, string password, long messageId, int lastid, int count)
        {
            return base.Channel.GetCampaignNumbersByMessageIdAsync(userName, password, messageId, lastid, count);
        }
        
        public System.Threading.Tasks.Task<avanak.Numbers[]> GetCampaignNumbersBySendDateAsync(string userName, string password, string fromDate, string toDate)
        {
            return base.Channel.GetCampaignNumbersBySendDateAsync(userName, password, fromDate, toDate);
        }
        
        public System.Threading.Tasks.Task<avanak.Numbers[]> GetCampaignNumbersDataByIdsAsync(string userName, string password, string campaignNumberIds)
        {
            return base.Channel.GetCampaignNumbersDataByIdsAsync(userName, password, campaignNumberIds);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<avanak.GetCampaignNumberStatusByIdResponse> avanak.WebService3Soap.GetCampaignNumberStatusByIdAsync(avanak.GetCampaignNumberStatusByIdRequest request)
        {
            return base.Channel.GetCampaignNumberStatusByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<avanak.GetCampaignNumberStatusByIdResponse> GetCampaignNumberStatusByIdAsync(string userName, string password, long campaignNumberId)
        {
            avanak.GetCampaignNumberStatusByIdRequest inValue = new avanak.GetCampaignNumberStatusByIdRequest();
            inValue.userName = userName;
            inValue.password = password;
            inValue.campaignNumberId = campaignNumberId;
            return ((avanak.WebService3Soap)(this)).GetCampaignNumberStatusByIdAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<int[]> GetCampaignNumbersStatusByIdsAsync(string userName, string password, string campaignNumberIds)
        {
            return base.Channel.GetCampaignNumbersStatusByIdsAsync(userName, password, campaignNumberIds);
        }
        
        public System.Threading.Tasks.Task<int> QuickSendAsync(string userName, string password, int messageId, string number, bool vote, int serverid)
        {
            return base.Channel.QuickSendAsync(userName, password, messageId, number, vote, serverid);
        }
        
        public System.Threading.Tasks.Task<int> QuickSendWithTTSAsync(string userName, string password, string text, string number, bool vote, int serverid, string CallFromMobile)
        {
            return base.Channel.QuickSendWithTTSAsync(userName, password, text, number, vote, serverid, CallFromMobile);
        }
        
        public System.Threading.Tasks.Task<string> SendOTPAsync(string userName, string password, int Length, string number, string text, int serverid)
        {
            return base.Channel.SendOTPAsync(userName, password, Length, number, text, serverid);
        }
        
        public System.Threading.Tasks.Task<avanak.OCVSend> SendOCVAsync(string userName, string password, string number, string callbackUrl, int serverid)
        {
            return base.Channel.SendOCVAsync(userName, password, number, callbackUrl, serverid);
        }
        
        public System.Threading.Tasks.Task<avanak.GetQuickSendResponse> GetQuickSendAsync(avanak.GetQuickSendRequest request)
        {
            return base.Channel.GetQuickSendAsync(request);
        }
        
        public System.Threading.Tasks.Task<decimal> GetTotalCostByDateAsync(string userName, string password, string fromDate, string toDate)
        {
            return base.Channel.GetTotalCostByDateAsync(userName, password, fromDate, toDate);
        }
        
        public System.Threading.Tasks.Task<avanak.Message> GetMessageAsync(string userName, string password, int messageId)
        {
            return base.Channel.GetMessageAsync(userName, password, messageId);
        }
        
        public System.Threading.Tasks.Task<avanak.Message[]> GetMessagesAsync(string userName, string password)
        {
            return base.Channel.GetMessagesAsync(userName, password);
        }
        
        public System.Threading.Tasks.Task<avanak.MessagesByPage> GetMessagesByPageAsync(string userName, string password, bool showPersist, int count, int currentpage, string order)
        {
            return base.Channel.GetMessagesByPageAsync(userName, password, showPersist, count, currentpage, order);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<avanak.DownloadMessageResponse> avanak.WebService3Soap.DownloadMessageAsync(avanak.DownloadMessageRequest request)
        {
            return base.Channel.DownloadMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<avanak.DownloadMessageResponse> DownloadMessageAsync(string userName, string password, int messageId)
        {
            avanak.DownloadMessageRequest inValue = new avanak.DownloadMessageRequest();
            inValue.userName = userName;
            inValue.password = password;
            inValue.messageId = messageId;
            return ((avanak.WebService3Soap)(this)).DownloadMessageAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<decimal> GetCreditAsync(string userName, string password)
        {
            return base.Channel.GetCreditAsync(userName, password);
        }
        
        public System.Threading.Tasks.Task<string> GetExpirationDateAsync(string userName, string password)
        {
            return base.Channel.GetExpirationDateAsync(userName, password);
        }
        
        public System.Threading.Tasks.Task<avanak.PriceViewModel> GetPricesAsync(string userName, string password)
        {
            return base.Channel.GetPricesAsync(userName, password);
        }
        
        public System.Threading.Tasks.Task<avanak.UserInfo> GetAccountInfoAsync(string userName, string password)
        {
            return base.Channel.GetAccountInfoAsync(userName, password);
        }
        
        public System.Threading.Tasks.Task<avanak.Transactions[]> GetTransactionsAsync(string userName, string password)
        {
            return base.Channel.GetTransactionsAsync(userName, password);
        }
        
        public System.Threading.Tasks.Task<int> AddTicketAsync(string userName, string password, string title, string text, int priority)
        {
            return base.Channel.AddTicketAsync(userName, password, title, text, priority);
        }
        
        public System.Threading.Tasks.Task<avanak.Ticket[]> GetTicketsAsync(string userName, string password, int lastId)
        {
            return base.Channel.GetTicketsAsync(userName, password, lastId);
        }
        
        public System.Threading.Tasks.Task<int> GetTicketStatusAsync(string userName, string password, int ticketId)
        {
            return base.Channel.GetTicketStatusAsync(userName, password, ticketId);
        }
        
        public System.Threading.Tasks.Task<int> MakeSecureCallAsync(string userName, string password, string srcNumber, string dstNumber, int holdMessageId, int serverId)
        {
            return base.Channel.MakeSecureCallAsync(userName, password, srcNumber, dstNumber, holdMessageId, serverId);
        }
        
        public System.Threading.Tasks.Task<int> GetAreaByNumberAsync(string userName, string password, string number)
        {
            return base.Channel.GetAreaByNumberAsync(userName, password, number);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebService3Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebService3Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebService3Soap))
            {
                return new System.ServiceModel.EndpointAddress("https://portal.avanak.ir/webservice3.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebService3Soap12))
            {
                return new System.ServiceModel.EndpointAddress("https://portal.avanak.ir/webservice3.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebService3Soap,
            
            WebService3Soap12,
        }
    }
}
